import Head from "next/head";
import type { Metadata } from "next";

// These styles apply to every route in the application
import "./globals.css";

export const metadata: Metadata = {
  title: "Tze Jie's website",
  description: "Generated by Create Next App",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <title>metadata.title</title>
        <meta charSet="utf-8" />
      </Head>
      <body>{children}</body>
    </html>
  );
}
